// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A visa recommendation AI agent.
 *
 * - visaRecommendation - A function that handles the visa recommendation process.
 * - VisaRecommendationInput - The input type for the visaRecommendation function.
 * - VisaRecommendationOutput - The return type for the visaRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const VisaRecommendationInputSchema = z.object({
  background: z
    .string()
    .describe(
      'The users professional and educational background, including years of experience, education level and field of study'
    ),
  budget: z.number().describe('The users budget in USD for the visa application process'),
  preferences: z
    .string()
    .describe(
      'Any preferences the user has for the visa, such as location, duration, or other factors.'
    ),
});
export type VisaRecommendationInput = z.infer<typeof VisaRecommendationInputSchema>;

const VisaRecommendationOutputSchema = z.object({
  visaOptions: z
    .array(z.string())
    .describe(
      'A list of visa options that are recommended for the user, based on their background, budget, and preferences.'
    ),
  reasoning: z
    .string()
    .describe(
      'A detailed explanation of why these visa options are recommended, and how they align with the users background, budget, and preferences.'
    ),
});
export type VisaRecommendationOutput = z.infer<typeof VisaRecommendationOutputSchema>;

export async function visaRecommendation(input: VisaRecommendationInput): Promise<VisaRecommendationOutput> {
  return visaRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'visaRecommendationPrompt',
  input: {schema: VisaRecommendationInputSchema},
  output: {schema: VisaRecommendationOutputSchema},
  prompt: `You are an expert visa consultant. You will provide personalized visa recommendations to users based on their background, budget, and preferences.

Background: {{{background}}}
Budget: {{{budget}}}
Preferences: {{{preferences}}}

Based on this information, recommend the most suitable visa options for the user, and explain why these options are a good fit.

{{#each visaOptions}}
  - {{{this}}}
{{/each}}

Reasoning: {{{reasoning}}}`,
});

const visaRecommendationFlow = ai.defineFlow(
  {
    name: 'visaRecommendationFlow',
    inputSchema: VisaRecommendationInputSchema,
    outputSchema: VisaRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
